# Auto-generated by proton-drive-cli-brew from Proton's release manifest.
# Do not edit by hand — run `update.sh` (CI keeps it current).
class ProtonDriveCli < Formula
  desc "Access Proton Drive end-to-end encrypted cloud storage from the terminal"
  homepage "https://proton.me/drive"
  version "0.6.0"
  license "MIT"

  # Prebuilt x86_64 Linux bottle so `brew install` pours it with no C compiler
  # (Homebrew-on-Linux otherwise requires one — a problem on atomic distros).
  # macOS and other arches fall back to the direct-from-Proton url below; macOS
  # always has clang via the required Command Line Tools, so no bottle is needed.
  bottle do
    root_url "https://github.com/jakobhviid/proton-drive-cli-brew/releases/download/v0.6.0"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "533468f681eeb2d865da6c562edc359e938c283d8f46897d17ed8c9aafc75ad8"
  end

  on_macos do
    on_arm do
      url "https://proton.me/download/drive/cli/0.6.0/darwin-arm64/proton-drive"
      sha256 "606a9736bb1dbdf45b9ced5452c77f01ebf46e329d494668bfd82421cc53e0b0"
    end
    on_intel do
      url "https://proton.me/download/drive/cli/0.6.0/darwin-x64/proton-drive"
      sha256 "0f2a66f002bde69e2c3ceefc256304fe9d13d7c7cf18c96429fc9dc5a0a82c3b"
    end
  end

  on_linux do
    on_arm do
      url "https://proton.me/download/drive/cli/0.6.0/linux-arm64/proton-drive"
      sha256 "5ab774a71fff67b591ef569ea19c20bcfc5bcab3a41976de2a2001825acfaf0d"
    end
    on_intel do
      url "https://proton.me/download/drive/cli/0.6.0/linux-x64/proton-drive"
      sha256 "0c268763bf9cf5e2d18f5cd05e79c63d2b26a996a670f5cddca1d9cfe0a02012"
    end
  end

  # Proton names the binary `proton-drive`; keep that so their docs' commands
  # work verbatim. The *formula* is proton-drive-cli to avoid the main app's name.
  def install
    bin.install "proton-drive"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/proton-drive version")
  end
end
