#!/usr/bin/env bash
# Regenerate the Homebrew formula for the Proton Drive CLI from Proton's own
# release manifest, AND build an x86_64 Linux *bottle* so `brew install` pours it
# with no C compiler (Homebrew-on-Linux requires one for non-bottled formulae).
# macOS and other arches fall back to the direct-from-Proton url in the formula.
#
# Proton publishes a versioned per-platform binary + a SHA-512 each; Homebrew
# needs a SHA-256, so we download each binary, verify Proton's SHA-512, then
# compute the SHA-256. The Linux binary is repackaged (no compile) into a bottle.
#
# Usage: ./update.sh [OUTPUT.rb]     (default: proton-drive-cli.rb)
# Outputs the version on stdout; writes the bottle to $WORK (default ./build).
# Requires: curl, jq, sha256sum, sha512sum, tar.
set -euo pipefail

MANIFEST="https://proton.me/download/drive/cli/version.json"
OUT="${1:-proton-drive-cli.rb}"
REPO="jakobhviid/proton-drive-cli-brew" # where the Linux bottle is released
WORK="${WORK:-$(pwd)/build}"
PLATFORMS=(macos/arm64 macos/x64 linux/arm64 linux/x64)

json="$(curl -fsSL "$MANIFEST")"
rel="$(jq -c '[.Releases[] | select(.CategoryName=="Stable")][0]' <<<"$json")"
version="$(jq -r '.Version' <<<"$rel")"
[ -n "$version" ] && [ "$version" != "null" ] || { echo "no stable version in manifest" >&2; exit 1; }
echo "Proton Drive CLI — stable $version" >&2

# Download each binary, verify Proton's SHA-512, compute the SHA-256 Homebrew
# needs. Keep the linux/x64 binary around to build the bottle.
declare -A URL SHA256
linux_x64_bin=""
for plat in "${PLATFORMS[@]}"; do
  url="$(jq -r --arg p "$plat" '.Files[] | select(.Platform==$p) | .Url' <<<"$rel")"
  sha512="$(jq -r --arg p "$plat" '.Files[] | select(.Platform==$p) | .Sha512CheckSum' <<<"$rel")"
  [ -n "$url" ] && [ "$url" != "null" ] || { echo "missing $plat in manifest" >&2; exit 1; }
  tmp="$(mktemp)"
  echo "  fetching $plat …" >&2
  curl -fsSL "$url" -o "$tmp"
  echo "${sha512}  ${tmp}" | sha512sum -c - >/dev/null
  URL[$plat]="$url"
  SHA256[$plat]="$(sha256sum "$tmp" | cut -d' ' -f1)"
  if [ "$plat" = "linux/x64" ]; then linux_x64_bin="$tmp"; else rm -f "$tmp"; fi
done

# Build the x86_64_linux bottle: a tar.gz of the keg layout Homebrew would install
# (proton-drive-cli/<version>/bin/proton-drive). No compilation — just repackaging.
mkdir -p "$WORK"
stage="$WORK/stage"
keg="$stage/proton-drive-cli/${version}/bin"
rm -rf "$stage"; mkdir -p "$keg"
mv "$linux_x64_bin" "$keg/proton-drive"
chmod +x "$keg/proton-drive"
bottle="$WORK/proton-drive-cli-${version}.x86_64_linux.bottle.tar.gz"
rm -f "$WORK"/*.bottle.tar.gz
( cd "$stage" && tar czf "$bottle" proton-drive-cli )
rm -rf "$stage"
BOTTLE_SHA256="$(sha256sum "$bottle" | cut -d' ' -f1)"
echo "  built bottle $(basename "$bottle")" >&2

root_url="https://github.com/${REPO}/releases/download/v${version}"

cat >"$OUT" <<EOF
# Auto-generated by proton-drive-cli-brew from Proton's release manifest.
# Do not edit by hand — run \`update.sh\` (CI keeps it current).
class ProtonDriveCli < Formula
  desc "Access Proton Drive end-to-end encrypted cloud storage from the terminal"
  homepage "https://proton.me/drive"
  version "${version}"
  license "MIT"

  # Prebuilt x86_64 Linux bottle so \`brew install\` pours it with no C compiler
  # (Homebrew-on-Linux otherwise requires one — a problem on atomic distros).
  # macOS and other arches fall back to the direct-from-Proton url below; macOS
  # always has clang via the required Command Line Tools, so no bottle is needed.
  bottle do
    root_url "${root_url}"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "${BOTTLE_SHA256}"
  end

  on_macos do
    on_arm do
      url "${URL[macos/arm64]}"
      sha256 "${SHA256[macos/arm64]}"
    end
    on_intel do
      url "${URL[macos/x64]}"
      sha256 "${SHA256[macos/x64]}"
    end
  end

  on_linux do
    on_arm do
      url "${URL[linux/arm64]}"
      sha256 "${SHA256[linux/arm64]}"
    end
    on_intel do
      url "${URL[linux/x64]}"
      sha256 "${SHA256[linux/x64]}"
    end
  end

  # Proton names the binary \`proton-drive\`; keep that so their docs' commands
  # work verbatim. The *formula* is proton-drive-cli to avoid the main app's name.
  def install
    bin.install "proton-drive"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/proton-drive version")
  end
end
EOF

echo "wrote $OUT (v$version) + $(basename "$bottle")" >&2
echo "$version"
