#!/usr/bin/env bash
# Regenerate the Homebrew formula for the Proton Drive CLI from Proton's own
# release manifest. Proton publishes a versioned, per-platform binary + a SHA-512
# for each; Homebrew needs a SHA-256, so we download each binary, verify Proton's
# SHA-512 (integrity), then compute the SHA-256 for the formula.
#
# Usage: ./update.rb.sh [OUTPUT.rb]   (default: proton-drive-cli.rb)
# Requires: curl, jq, sha256sum, sha512sum.
set -euo pipefail

MANIFEST="https://proton.me/download/drive/cli/version.json"
OUT="${1:-proton-drive-cli.rb}"

# macOS/Linux, arm64 + x86_64. (Proton also ships musl + Windows; Homebrew wants
# glibc on Linux and doesn't target Windows, so we take the glibc/native four.)
PLATFORMS=(macos/arm64 macos/x64 linux/arm64 linux/x64)

json="$(curl -fsSL "$MANIFEST")"
rel="$(jq -c '[.Releases[] | select(.CategoryName=="Stable")][0]' <<<"$json")"
version="$(jq -r '.Version' <<<"$rel")"
[ -n "$version" ] && [ "$version" != "null" ] || { echo "no stable version in manifest" >&2; exit 1; }
echo "Proton Drive CLI — stable $version" >&2

declare -A URL SHA256
for plat in "${PLATFORMS[@]}"; do
  url="$(jq -r --arg p "$plat" '.Files[] | select(.Platform==$p) | .Url' <<<"$rel")"
  sha512="$(jq -r --arg p "$plat" '.Files[] | select(.Platform==$p) | .Sha512CheckSum' <<<"$rel")"
  [ -n "$url" ] && [ "$url" != "null" ] || { echo "missing $plat in manifest" >&2; exit 1; }
  tmp="$(mktemp)"
  echo "  fetching $plat …" >&2
  curl -fsSL "$url" -o "$tmp"
  echo "${sha512}  ${tmp}" | sha512sum -c - >/dev/null   # verify Proton's checksum
  URL[$plat]="$url"
  SHA256[$plat]="$(sha256sum "$tmp" | cut -d' ' -f1)"
  rm -f "$tmp"
done

cat >"$OUT" <<EOF
# Auto-generated by proton-drive-cli-brew from Proton's release manifest.
# Do not edit by hand — run \`update.sh\` (CI keeps it current).
class ProtonDriveCli < Formula
  desc "Access Proton Drive end-to-end encrypted cloud storage from the terminal"
  homepage "https://proton.me/drive"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${URL[macos/arm64]}"
      sha256 "${SHA256[macos/arm64]}"
    end
    on_intel do
      url "${URL[macos/x64]}"
      sha256 "${SHA256[macos/x64]}"
    end
  end

  on_linux do
    on_arm do
      url "${URL[linux/arm64]}"
      sha256 "${SHA256[linux/arm64]}"
    end
    on_intel do
      url "${URL[linux/x64]}"
      sha256 "${SHA256[linux/x64]}"
    end
  end

  # Proton names the binary \`proton-drive\`; keep that so their docs' commands
  # work verbatim. The *formula* is proton-drive-cli to avoid the main app's name.
  def install
    bin.install "proton-drive"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/proton-drive version")
  end
end
EOF

echo "wrote $OUT (version $version)" >&2
echo "$version"
